steps:
# Build the container image from the twilioflex directory
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/agentspace-notebookllm-ent/agent-assist-repo/mimico-twilio-webhook:latest', './twilioflex/agent-assist-functions']
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/agentspace-notebookllm-ent/agent-assist-repo/mimico-twilio-webhook:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'mimico-twilio-webhook'
  - '--image'
  - 'us-central1-docker.pkg.dev/agentspace-notebookllm-ent/agent-assist-repo/mimico-twilio-webhook:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--quiet'
images:
- 'us-central1-docker.pkg.dev/agentspace-notebookllm-ent/agent-assist-repo/mimico-twilio-webhook:latest'
